@MachineService_HostAddress = http://localhost:5295

###

POST {{MachineService_HostAddress}}/api/machine/cycle
Content-Type: application/json

{
  "sampleId": "good-part"
}

### Missing-feature rejection sample

POST {{MachineService_HostAddress}}/api/machine/cycle
Content-Type: application/json

{
  "sampleId": "missing-hole"
}

GET {{MachineService_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MachineService_HostAddress}}/api/events?page=1&pageSize=25

###

GET {{MachineService_HostAddress}}/api/cycles?page=1&pageSize=25

###

GET {{MachineService_HostAddress}}/api/faults?page=1&pageSize=25

###

GET {{MachineService_HostAddress}}/api/metrics

###

POST {{MachineService_HostAddress}}/api/simulation/faults/robot-communication

###

POST {{MachineService_HostAddress}}/api/simulation/faults/robot-communication/clear

###

POST {{MachineService_HostAddress}}/api/simulation/faults/clear
